// <auto-generated />
using System;
using IMSTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250507155935_AddKontrakNoColumn")]
    partial class AddKontrakNoColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("IMSTest.Models.Angsuran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AngsuranKe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AngsuranPerBulan")
                        .HasColumnType("TEXT");

                    b.Property<int>("KontrakId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalJatuhTempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KontrakId");

                    b.ToTable("Angsuran");
                });

            modelBuilder.Entity("IMSTest.Models.Kontrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontrakNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OTR")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kontrak");
                });

            modelBuilder.Entity("IMSTest.Models.Angsuran", b =>
                {
                    b.HasOne("IMSTest.Models.Kontrak", "Kontrak")
                        .WithMany("ListAngsuran")
                        .HasForeignKey("KontrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("IMSTest.Models.Kontrak", b =>
                {
                    b.Navigation("ListAngsuran");
                });
#pragma warning restore 612, 618
        }
    }
}
